---
# tasks file for spinerole
- name: Adding System Hostname
  nclu:
    commands:
       - add hostname {{ item.hostname_sw }}
    commit: true
  with_items:
    - "{{ bgpevpn }}"
- name: configure {{ item.hostname_sw }} interfaces uplink to spine
  nclu:
    commands:
       - add interface swp1-6 alias LINK_TO_LEAF_SWITCHES
    commit: true
  with_items:
    - "{{ bgpevpn }}"
- name: Configure loopback address
  nclu:
    commands:
       - add loopback lo ip address {{ item.loopback_ip }}/32
    commit: true
  with_items:
    - "{{ bgpevpn }}"
- name: Set MTU for interfaces LINK_TO_LEAF_SWITCHES
  nclu:
    commands:
       - add interface swp1-6 mtu 9216
- name: Set IPv6 configuration on LINK_TO_LEAF_SWITCHES
  nclu:
    commands:
       - add interface swp1-6 ipv6 nd suppress-ra
       - add interface swp1-6 ipv6 nd ra-interval 5
    commit: true

- name: BGP Basic
  nclu:
    commands:
           - add bgp autonomous-system {{ item.asn }}
           - add bgp router-id {{ item.loopback_ip }}
           - add bgp bestpath as-path multipath-relax
           - add bgp neighbor LEAF peer-group
           - add bgp neighbor LEAF remote-as external
           - add bgp neighbor LEAF capability extended-nexthop
           - add bgp neighbor swp1-6 interface peer-group LEAF
           - add bgp ipv4 unicast network {{ item.loopback_ip }}/32
    commit: true
  with_items:
    - "{{ bgpevpn }}"
- name: BGP EVPN
  nclu:
    commands:
           - add bgp l2vpn evpn neighbor LEAF activate
           - add bgp l2vpn evpn advertise-all-vni
    commit: true
