---
- name: Deploying spine switches for EVPN fabric
  hosts: spine
  roles:
  - spine

- name: Deploying leaf switches for EVPN fabric
  hosts: leaf
  roles:
  - leaf

- name: Deploying exit/border switches for EVPN fabric
  hosts: exit
  roles:
  - exit
