---
#- name: Deploying spine switches for EVPN fabric
#  hosts: spine
#  roles:
#   - common
#   - spine

- name: Deploying leaf switches for EVPN fabric
  hosts: leaf
  gather_facts: yes
  roles:
    # - common
  - leaf

    #- name: Deploying exit/border switches for EVPN fabric
#  hosts: exit
    #roles:
#  - common
# - exit
