---
- name: EVPN deploying spine
  hosts: spine
  remote_user: cumulus
  vars:
    bgpevpn:
      - { loopback_ip: 10.0.0.1, hostname_sw: spine01, asn: 65003 }
      - { loopback_ip: 10.0.0.2, hostname_sw: spine02, asn: 65003 }
  roles:
  - spinerole

- name: EVPN deploying leaf
  hosts: leaf
  remote_user: cumulus
  roles:
  - leafrole
  vars:
    vrf_customer: "bbcore"
    l3vni_vlan: "4001"
    l3vni_name: "vnil3-bbcore"
    l3vxlan_id: "104001"
    vlan: [ 201, 202, 301, 302 ]
    bgpevpn:
      - { loopback_ip: 10.0.0.3, hostname_sw: leaf01, asn: 65001 }
      - { loopback_ip: 10.0.0.4, hostname_sw: leaf02, asn: 65002 }
    vxlan:
      - { name: vni201, id: 10201, vid: 201, gw: 172.16.201.1/24 }
      - { name: vni202, id: 10202, vid: 202, gw: 172.16.202.1/24 }
      - { name: vni301, id: 10301, vid: 301, gw: 172.16.103.1/24 }
      - { name: vni302, id: 10302, vid: 302, gw: 172.16.102.1/24 }
