---
# tasks file for common
- name: Adding cumulus users sshkeys
  authorized_key:
    user: "{{ item }}"
    key:  "{{ lookup('file', 'roles/common/vars/certs/id_belloau.pub')}}"
  with_items:
    - "{{ cumulususers }}"
- name: Ports conf
  become_user: true
  template:
    src=roles/common/vars/ports/{{ ansible_hostname }}.j2 dest=/etc/cumulus/ports.conf
  notify: Restart Switchd
- name: flush handlers
  meta: flush_handlers
- name: Configure SNMP Settings
  nclu:
    commands:
      - add snmp-server listening-address all
      - add snmp-server readonly-community "{{ snmppass }}" access any
      - add snmp-server trap-destination 10.20.0.50 community-password bearsnmp version 2c
    commit: true

- name: Removing default ntp servers setting
  nclu:
     commands:
       - del time ntp server {{ item }}
     commit: true
  with_items:
    - "{{ defaultntp }}"

- name: Configuring ntp servers
  nclu:
    commands:
      - add time ntp server {{ item }} iburst
    commit: true
  with_items:
    - "{{ ntpservers }}"

- name: configuring syslog servers
  nclu:
    commands:
        - add syslog host ipv4 {{ item }} port udp 514
    commit: true
  with_items:
    - "{{ syslogservers }}"
